name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" -e "set ftp:ssl-allow no; set ftp:passive-mode yes; set net:timeout 30; put -O /sites/dxascanlausanne.com/ index.html; quit" ftp.hosting-ik.com
