name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.hosting-ik.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /sites/dxascanlausanne.com/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
